name: Deploy Github Pages
on: [push]
jobs:
  Deploy-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm start build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
